# GCP "live demo" stack — Firebase Hosting (static) + Cloud Run (backend).
# The cheap, always-live environment linked from the README. See
# docs/GCP-DEV-PLAN.md for the full rationale and how it pairs with the AWS
# "reference" stack in infra/prod-aws.
#
# State backend (backend.tf) is generated by infra/dev-gcp/bootstrap.
# Firebase itself was enabled out-of-band (console ToS accept); the default
# <project>.web.app Hosting site already exists, so it's not managed here.

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.0"
    }
  }
  required_version = ">= 1.15"
}

provider "google" {
  project = var.project_id
  region  = var.region

  # Some APIs (billingbudgets, and other "requires a quota project" services)
  # reject user ADC unless the provider attaches a quota/billing project via the
  # X-Goog-User-Project header. Setting the ADC quota project alone isn't
  # enough — the provider only sends that header when user_project_override is
  # on. Harmless for the APIs that don't need it.
  user_project_override = true
  billing_project       = var.project_id
}

data "google_project" "this" {
  project_id = var.project_id
}

#----------------------------------------------------------
# API enablement
# disable_on_destroy = false: destroying this stack should not yank APIs that
# other things (or a future re-apply) may depend on.
#----------------------------------------------------------

locals {
  services = [
    "run.googleapis.com",
    "artifactregistry.googleapis.com",
    "firebasehosting.googleapis.com",
    "monitoring.googleapis.com",
    "billingbudgets.googleapis.com",
  ]
}

resource "google_project_service" "services" {
  for_each = toset(local.services)

  service            = each.value
  disable_on_destroy = false
}
