name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/live/**'
  workflow_dispatch: {}

permissions:
  id-token: write      # Required for AWS OIDC authentication
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.APPLY_ROLE_ARN_GITHUB }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./infra/live
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra/live
        run: terraform apply -auto-approve -no-color

      - name: Show outputs
        working-directory: ./infra/live
        run: terraform output
